### ISSUE TITLE
loading bar sometimes doesn't finish and go away

### ISSUE THREAD

**Issue by joshua-8** [P-B-and-J/SunMap#31]
we currently don't know how to reproduce the issue, but saw it once

**Comment by palmerc120** [comment]
Having a hard time reproducing the bug

**Comment by joshua-8** [comment]
Loading a folder that contains no photos (like going up one level and trying to load SunMap\Test Photos instead of one of the sets of images crashes the program and makes the loading bar never fill. I think we might be able to fix this by giving an error message and cancelling the loading of images if 0 images get loaded.

**Comment by joshua-8** [comment]
fixed
