### ISSUE TITLE
Make users accept license agreement

### ISSUE THREAD

**Issue by palmerc120** [P-B-and-J/SunMap#34]
Have a window pop up the first time the program is launched, and don't run the main program until it is accepted. Once accepted, save in file and don't show again unless requested by user (in settings page maybe?)

**Comment by joshua-8** [comment]
I'm not so sure that we want this, it's extra complexity and an inconvenience to users (and our current chosen license is extremely permissive anyways). We could add a very visible note in each release description on github linking to the terms, and we could include the license file with each executable.
What are your thoughts?
